### ISSUE TITLE
Product Image Gallery of navbar Admin manager

### ISSUE THREAD

**Issue by brendanstack** [TanHongIT/new-mvc-shop#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TanHongIT** [comment]
I'm checking again. Can you describe in more detail the error displayed, thanks

**Comment by brendanstack** [comment]
From what I see, at Image Gallery screen, the navbar didn't work as expected

**Comment by TanHongIT** [comment]
I checked and actually got an error with the navbars in the Image Gallery screen for the user with administrator rights.
And I have now fixed that, you can review my commit and be able to fix it:
https://github.com/TanHongIT/new-mvc-shop/commit/0699b23f275acfc7b8360e45cd3beed5cd1d82ac

**Comment by brendanstack** [comment]
Great! Thank you!
